### ISSUE TITLE
Styling from Fabric UI breaks the header in new release wave

### ISSUE THREAD

**Issue by TheosNz** [garethcheyne/PCF-NZBN-AutoComplete#12]
Looks like the native Fabric UI used by CRM is sharing some of the class names as the Fabric UI CSS file used in this component and causing the header to break.
![MicrosoftTeams-image (17)](https://user-images.githubusercontent.com/26403644/194201301-e2f234ed-5346-4634-abfd-981e8031bc81.png)

**Comment by garethcheyne** [comment]
Hi TheosNz,

Please note this is just a sample project and I don't maintain it. I rebuilt this awhile ago for my own production env.

If you are running this in a production env I would point you here.
[www.magnetismsolutions.com](https://www.magnetismsolutions.com/our-products/nzbn-connector-for-dynamics365)

Or feel free to clone the repo and change the styling.

Cheers.

**Comment by TheosNz** [comment]
No worries found this example from PCF Gallery and just wanted to let you know as obviously you just shared it to the community which is cool so was not sure if you wanted to keep it maintained for there.

Thanks!

**Comment by garethcheyne** [comment]
All good mate, I added you to LinkedIn
